apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring-dev
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      # URL interna do serviço do Prometheus. O Kubernetes resolve este DNS.
      url: http://prometheus-service:9090 
      access: proxy
      isDefault: true
