apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-llm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blackstile/k8s-day-sample.git
    targetRevision: feature/v3
    path: app-llm/k8s # Pasta com os manifestos da sua aplicação
  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
