apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blackstile/k8s-day-sample.git
    targetRevision: master
    path: observability/01-grafana # Pasta pai que contém as subpastas do Prometheus e Grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
