name: Build, Push, and Update Manifest

on:
  push:
    branches:
      - master
    paths:
      - 'app-llm/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
        with:
          length: 7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./app-llm
          file: ./app-llm/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-llm:${{ steps.commit.outputs.short }}

      - name: Update Kubernetes manifest
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
        
          NEW_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/app-llm:${{ steps.commit.outputs.short }}"

          echo -e "chamando o yq para atualizar o deployment "
          echo -e "NEW_IMAGE=${NEW_IMAGE}"

          # Edita o arquivo de deployment para usar a nova imagem.
          # Altere 'app-llm/k8s/deployment.yaml' se o caminho for diferente.
          yq e -i '.spec.template.spec.containers[0].image = strenv(NEW_IMAGE)' app-llm/k8s/02-deploy.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add app-llm/k8s/02-deploy.yaml
          
          if git diff --staged --quiet; then
            echo "Nenhuma mudança no manifesto para commitar."
          else
            git commit -m "ci: Atualiza tag da imagem para ${{ steps.commit.outputs.short }} [skip ci]"
            git push
          fi
