---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gemini-api-secret
  namespace: app-dev
spec:
  encryptedData:
    GEMINI_API_KEY: AgAZaI9YVvVaVzqgwZffCYRJgCvvs5HxnPF6akFznR3+bdWp5naT1kM9YkrZKF4oGRHIpnjpYnUqGbhE9NjLW8AHmrhpkjnO/kTud3ARpqHXLvXMgev/9ZsKqntoTYdyF6xMmWM6/lZWu8RXq1KfTh48NMAVKhmc/AjRuyuqChda9fhpkZLTesKiNNc8ZUntCvnrEIEvxqYBQRvn+5DKSFtvSXhe+xyGspoHmNpifKaki7n5mw2/KVcw9DgY+ZTwuqrSyirgo+OLcW6Us9rjjHCvMFKjOjc6HSogdlqXCh6NQpcFf2qmOYdAsmtM7iiIL15RU69zJCCiUdRvRKCZLNeZVqsQusiiAXrngMFUnxH46Ue57hdqSVjuL0+vkj4/00b+HiZLJ6TeARc3ycTMKyaAV6YjE1rO1vbmINyIXxo7uHAGbAQJGV5ZghGUk/Nln+ZarNfYRGlhgtB+CT+xVrjuMekKmHIWEavbE6lhdmGo/gluwH/Pv6mJ0d52mMeMTOwSj2eOM+YEIHr+ewUAkhwZG01DBcoRHWIYzXG6mquojHmP/r2nKpZNRCK9W9N9mzMaCPb1GgWsXL40C+8iO3MzO++e6+wlcBQtqfRfQfS3LHvFjfns5ENWKNioPvewPdSo89tnMtaho+z4F+bx1t2JU2gLVboSfIwoUmTGvuLHGRWBLjNvlj2YFOYeFTM+/wn7yyoDjtwzBHid7gV1Z7vE2Evu5cvb1DAlOPBXmgnlIZ5M7envs1I=
  template:
    metadata:
      creationTimestamp: null
      name: gemini-api-secret
      namespace: app-dev
    type: Opaque
